[package]
name = "simple-generated"
version = "0.1.0"
authors = ["randymcmillan <randymcmillan@protonmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.28.1"
color-eyre = "0.6.3"
